"""
Construct and simulate one participant-specific FCDT block.
"""

from types import SimpleNamespace                                               # simple namespace
import pandas as pd                                                             # simulation trial template
from abm_mdp import abm_mdp                                                     # MDP structure definition
from abm_abm import abm_abm                                                     # ABM inference and simulation utility        

def abm_simulate(sim):                                                          # simulate one participant-specific FCDT block
    """
    Simulate one block using its experimental design and agent parameters.

    Input
        sim : SimpleNamespace() object with required attributes:
            .X.D   : experimental design database (dict)
            .X.SL  : stimulus catalogue (pandas.DataFrame)
            .X.T1  : Task 1 identifier, e.g. 'PTD'
            .X.T2  : Task 2 identifier, e.g. 'RMC'
            .X.P   : participant identifier (string)
            .X.R   : run identifier (string)
            .X.B   : task repetition block identifier (string)
            .X.n   : number of actions (positive integer)
            .θ     : physical parameter vector (beta, sigma, tau)
            .agent : agent identifier, 'A0' or 'A1'
            .O     : response onset, or numpy.nan when unavailable

    Output
        sim : input SimpleNamespace with the new attribute:
            .P : ABM namespace with .θ, .blocks, and simulated trials in .D

    A1 uses all three entries of .θ. A0 receives P.θ = None and selects
    actions uniformly. Its simulation labels still use sim.θ.
    Trial indices run from zero to .X.n - 1. The block's .df contains these
    indices and the planned P, R, B, C, and O metadata. States, actions,
    and rewards are generated by the ABM, not specified by the template.
    """
    # experimental design-based simulation specifications
    # -------------------------------------------------------------------------
    P         = SimpleNamespace()                                               # experimental design structure
    P.P       = sim.X.P                                                         # participant ID
    P.R       = sim.X.R                                                         # run number
    P.B       = sim.X.B                                                         # task repetition block
    P.T1      = sim.X.T1                                                        # task 1
    P.T2      = sim.X.T2                                                        # task 2
    P.n       = sim.X.n                                                         # maximum number of actions
    P.SL      = sim.X.SL                                                        # stimulation labels
    P.S1L     = P.SL[P.SL.task_type == P.T1].sort_values('stimulus_id')         # task 1 stimulus table
    P.S2L     = P.SL[P.SL.task_type == P.T2].sort_values('stimulus_id')         # task 2 stimulus table
    P.S1L     = P.S1L.stimulus_name.tolist()                                    # task 1 stimulus labels
    P.S2L     = P.S2L.stimulus_name.tolist()                                    # task 2 stimulus labels
    P.TP      = f"{P.T1}-{P.T2}"                                                # dual-task condition
    P.BLK     = sim.X.D['participants'][P.P][P.TP][P.R][P.B]                    # task repetition block
    P.S1T     = P.BLK['S1T']                                                    # task 1 target labels
    P.S2T     = P.BLK['S2T']                                                    # task 2 target labels

    # simulation
    # -------------------------------------------------------------------------
    b         = SimpleNamespace()                                               # abm_abm parameter            
    b.mdp     = abm_mdp(P)                                                      # MDP structure definition
    b.df      = pd.DataFrame(index = range(P.n))                                # one template row per planned trial
    b.df['P'] = int(P.P)                                                        # participant identifier
    b.df['R'] = int(P.R)                                                        # run identifier
    b.df['B'] = int(P.BLK['source_block'])                                      # experimental block identifier
    b.df['C'] = P.TP                                                            # dual-task condition
    b.df['O'] = sim.O                                                           # response onset
    b.df['t'] = range(P.n)                                                      # zero-based trial indices
    P         = SimpleNamespace()                                               # shared simulation settings
    P.mode    = 'gen'                                                           # generative mode
    P.agent   = sim.agent                                                       # selected agent
    P.θ       = sim.θ if sim.agent == 'A1' else None                            # physical parameters for A1, none for A0
    P.blocks  = [b]                                                             # one-block collection for this simulation caller
    P         = abm_abm(P)                                                      # run simulation


    # output
    # -------------------------------------------------------------------------
    sim.P     = P                                                               # abm_abm parameter

    return sim
